var json = {
	"services":[{
		"title":"服务介绍",
		"row":[{
				"h4":"品牌",
				"p":"根据品牌文化、价值观和差异性制定品牌策略，设计LOGO/VI系统；我们以前瞻性的眼光创造独特的品牌认同",
				"classa":"",
				"classb":"fa-apple"
			},{
				"h4":"包装",
				"p":"包装设计的好坏，对于产品至关重要，直接关系产品的市场表现；我们拥有丰富的成功案例，专业且追求极致",
				"classa":"d1",
				"classb":"fa-dropbox"
			},{
				"h4":"广告",
				"p":"广告创意、宣传物料设计对于线上线下市场活动必不可少；快速反应和超强的执行力是我们对客户的郑重承诺",
				"classa":"d2",
				"classb":"fa-pencil"
			},{
				"h4":"网站",
				"p":"互联网是一个变化、持续创新的互动平台；我们应用最新的设计理念和技术方案，助您高效的连接每一位客户",
				"classa":"d3",
				"classb":"fa-html5"
			}]
			
	}],
	"portfolio":{
		"main":[{
			"images":"img/10.jpg,img/10-1.jpg,img/10-2.jpg",
			"src":"img/10-3.jpg",
			"h2":"途家盛捷服务公寓",
			"p":"品牌（LOGO/VI）"
		},{
			"images":"img/9-3.jpg,img/9-5.jpg,img/9-6.jpg",
			"src":"img/9-1.jpg",
			"h2":"MODELAB/爱慕内衣",
			"p":"品牌（LOGO/VI）"
		},{
			"images":"img/8-1.jpg,img/8-3.jpg,img/8-4.jpg,img/8-5.jpg",
			"src":"img/8_.jpg",
			"h2":"觉",
			"p":"品牌（LOGO/VI）"
		},{
			"images":"img/11-1.jpg,img/11-2.jpg,img/11-3.jpg",
			"src":"img/11.jpg",
			"h2":"CNZCO兴宇中科",
			"p":"品牌（LOGO/VI）"
		},{
			"images":"img/5-1.jpg,img/5-2.jpg",
			"src":"img/5_.jpg",
			"h2":"同仁堂保健酒",
			"p":"包装（packing）"
		},{
			"images":"img/13.jpg,img/13-1.jpg",
			"src":"img/13.jpg",
			"h2":"伊利乳品",
			"p":"包装（packing）"
		},{
			"images":"img/4-1.jpg,img/4-2.jpg,img/4-3.jpg,img/4-4.jpg,img/4-5.jpg",
			"src":"img/4.jpg",
			"h2":"雀巢咖啡",
			"p":"包装（packing）"
		},{
			"images":"img/15-1.jpg,img/15-2.jpg,img/15-3.jpg,img/15-4.jpg",
			"src":"img/15.jpg",
			"h2":"雀巢礼盒",
			"p":"包装（packing）"
		},{
			"images":"img/14-1.jpg,img/14-2.jpg,img/14-3.jpg,img/14-4.jpg,img/14-5.jpg",
			"src":"img/14.jpg",
			"h2":"雀巢广告",
			"p":"广告（advertising）"
		},{
			"images":"img/16-1.jpg,img/16-2.jpg,img/16-3.jpg",
			"src":"img/16.jpg",
			"h2":"沃尔沃",
			"p":"广告（advertising）"
		},{
			"images":"img/3-1.jpg,img/3-2.jpg",
			"src":"img/3.jpg",
			"h2":"黑猫神蚊香",
			"p":"广告（advertising）"
		},{
			"images":"img/7-1.jpg,img/7-2.jpg,img/7-3.jpg,img/7-4.jpg",
			"src":"img/7.jpg",
			"h2":"上京东抢零食",
			"p":"广告（advertising）"
		},{
			"images":"img/6-1.jpg,img/6-2.jpg",
			"src":"img/6.jpg",
			"h2":"安师傅",
			"p":"广告（advertising）"
		},{
			"images":"img/1-1.jpg,img/1-2.jpg,img/1-3.jpg,img/1-4.jpg",
			"src":"img/1.jpg",
			"h2":"M&M豆",
			"p":"广告（advertising）"
		},{
			"images":"img/2-1.jpg,img/2-2.jpg",
			"src":"img/2.jpg",
			"h2":"大众点评玩转迪拜",
			"p":"网站（website）"
		}]
	},
	"contact":{
		"src":["img/1.png","img/2.png","img/3.png","img/4.png","img/5.png","img/6.png","img/7.png","img/8.png","img/9.png","img/10.png","img/11.png","img/12.png"],
		"quotes":[{
			"p":"跟觅未合作很愉快，我们觉得觅未是一家很专业的品牌设计公司，这个团队非常棒，有激情、有创造力、有执行力，经常给我们带来很多好的IDEA，是我们合作过的供应商中设计水平比较高，非常值得信任的一家。",
			"h4":"东阿市场部 / 刘经理 "
		},{
			"p":"觅未是一家很用心的品牌设计公司，相比之前合作过的一些供应商，觅未的工作态度认真主动，项目进度控制严格，即便我们没有要求，他们也会主动做多款不同方向的设计稿供我们选择，与觅未合作我们很放心。",
			"h4":"雀巢市场部 / 张经理 "
		},{
			"p":"我们是通过一次比稿选择了觅未创意，他们除了设计能力突出之外，还有自己的技术研发团队，经营模式融合了互联网的服务理念，沟通流程扁平化，服务态度诚恳，执行效率高，是一家性价比很高的设计公司。",
			"h4":"伊利市场部 / 王经理 "
		}]
	}
}
